server:
  port: 9001

spring:
  messages:
    basename: i18n/lang
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: daye
    password: daye2019
    url: jdbc:mysql://www.tdd-nas.cn:3306/daye_billing?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false                                    #开发时关闭缓存,不然没法看到实时页面
    servlet:
      content-type: text/html
  cache:
    type: ehcache
    ehcache:
      config: ehcache.xml
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

mybatis-plus:
  type-aliases-package: com.daye.sys.entity
  mapper-locations: mapping/*Mapper.xml
  configuration:
    cache-enabled: true

logging:
  level:
    com:
      daye:
        sys:
          mapper : debug
