server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: daye
    password: daye2019
    url: jdbc:mysql://www.tdd-nas.cn:3306/daye_billing?characterEncoding=utf-8&useSSL=false

mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.daye.sys.entity
  configuration:
    cache-enabled: true

logging:
  level:
    com:
      daye:
        mapper : debug
